### PR TITLE
Improve logging

### LINKED ISSUE #1046: Improve logging of the launcher
Currently, the logs don't provide enough information to troubleshoot common problems.

Ideally, I think we've got to include:
 * IPC communications (https://github.com/hypermodules/electron-ipc-log)
 * Network failures
 * Electron errors
 * Separated logs for the headless

### PR DESCRIPTION
**Pull request by BasixKOR**
* [x] IPC communications (https://github.com/hypermodules/electron-ipc-log)
 * [ ] Network failures
 * [ ] Electron errors
 * [x] Separated logs for the headless
 
Closes #1046.

### CODE REVIEW

**Comment by dahlia** [comment]
@BasixKOR Is this still going on?

**Comment by BasixKOR** [comment]
Mostly no, although the need is still valid.

**Comment by dahlia** [comment]
Then, it would be better to this at present, and open a new pull request when you start to work on this again.  🤔

**Comment by BasixKOR** [comment]
Good point.

**Pull request closed without merging**
