### PR TITLE
Make direct state change while both player update and launcher update required

### LINKED ISSUE #1920: It causes blinking between player update and launcher update because of state machine goes to DONE when player update finished, and goes to launcher update directly after.
It causes blinking between player update and launcher update because of state machine goes to DONE when player update finished, and goes to launcher update directly after.
it seems fixable if we check IUpdate just before player update finishes and send state to launcher update.

_Originally posted by @Akamig in https://github.com/planetarium/9c-launcher/issues/1917#issuecomment-1249182308_

### PR DESCRIPTION
**Pull request by Akamig**
This Resolves #1920, but I'm not sure at certain points.

### CODE REVIEW

**Review by BasixKOR — COMMENTED** [review]
`invokeIpcEvent` should be invoked within the state listening to the event.

**Comment by Akamig** [comment]
I haven't tested yet, but it seems to work I guess...?

**Comment by Akamig** [comment]
Fixed condition, tested and confirmed it works like a charm.

**Review by BasixKOR — APPROVED** [review]
dunno, lgtm

**Pull request merged**
