### PR TITLE
Prevent double submitting on Send NCG screen

### LINKED ISSUE #1169: Prevent double submitting on `Send NCG` screen
When user click `Send` button twice or more, it seemed create sending txs that much.

### PR DESCRIPTION
**Pull request by x86chi**
Add loading status to button

close #1169 issue

### CODE REVIEW

**Comment by BasixKOR** [comment]
It appears that `@mui/lab` requires `@mui/material @emotion/react @emotion/styled` to be installed. Could you add them as well?

**Comment by BasixKOR** [comment]
image

Thanks! It works well now. However, I've noticed that the style has been changed drastically due to incompatibility with v4 and v5. How about using the [`CircularProgress`](https://v4.mui.com/api/circular-progress/#circularprogress-api) component?

**Comment by x86chi** [comment]
Screen Shot 2022-01-22 at 3 43 11 PM Done!

**Review by BasixKOR — APPROVED** [review]
Awesome!

**Pull request merged**
